#!/bin/bash -l

INSTALL_PATH=$( cd $( dirname ${BASH_SOURCE[0]} ) && pwd )

module purge
module load PrgEnv-gnu/4.6
module load python
module load hdf5/1.8.11
module load jamo
module load uge

python $INSTALL_PATH/catjob.py "$@"
