#define DEFAULT_FREQUENCY 30
#define DEFAULT_INITIAL_PHASE 30
#define DEFAULT_INITIAL_PHASE_FREQUENCY 1
#define DEFAULT_OUTPUT_FLAGS 4 /* AMQP output */
#define DEFAULT_IDENTIFIER "JOB_ID"
#define DEFAULT_SUBIDENTIFIER "SGE_TASK_ID"
#define DEFAULT_AMQP_HOST "genepool10.nersc.gov"
#define DEFAULT_AMQP_PORT 5672
#define DEFAULT_AMQP_VHOST "jgi"
#define DEFAULT_AMQP_USER "procmon"
#define DEFAULT_AMQP_PASSWORD "nomcorp"
#define DEFAULT_AMQP_EXCHANGE_NAME "procmon"
#define DEFAULT_AMQP_FRAMESIZE 131072
