#!/bin/bash

HN=$(hostname | sed -e 's/\..*//')
if [ -z "$HN" ]; then
	echo PROBLEM: bad hostname, $HN
	exit
fi

ID=
SUBID=
PROCUSER=procmon
PIDFILE=/var/run/procmon.pid

case $HN in
	gpweb*)
		ID='WEB'
	;;
	gpint*)
		ID='INT'
	;;
	genepool*)
		ID='LOGIN'
	;;
	*)
		ID='JGI'
	;;
esac

case $HN in
	gpint01)
		SUBID='RND'
	;;
	gpint12)
		SUBID='RND'
	;;
	gpint10[01])
		SUBID='RND'
	;;
	gpint10[234])
		SUBID='PLANT'
	;;
	gpint105)
		SUBID='IMG'
	;;
	gpint106)
		SUBID='GBP'
	;;
	gpint107)
		SUBID='SDM'
	;;
	gpint108)
		SUBID='RQC'
	;;
	gpint109)
		SUBID='ASSEMBLY'
	;;
	gpint110)
		SUBID='ASSEMBLY'
	;;
	gpint111)
		SUBID='VISTA'
	;;
	gpint112)
		SUBID='GENERAL'
	;;
	gpint0[23])
		SUBID='VISTA'
	;;
	gpint0[45])
		SUBID='IMG'
	;;
	gpint0[6])
		SUBID='GBP'
	;;
	gpint0[789])
		SUBID='PLANT'
	;;
	gpint1[01])
		SUBID='PLANT'
	;;
	gpint13)
		SUBID='FUNGAL'
	;;
	gpint1[456789])
		SUBID='GENERAL'
	;;
	gpint2[012])
		SUBID='GENERAL'
	;;
	gpint2[367])
		SUBID='SDM'
	;;
	gpint2[45])
		SUBID='RQC'
	;;
	gpweb0[12])
		SUBID='VISTA'
	;;
	gpweb0[4567])
		SUBID='IMG'
	;;
	gpweb08)
		SUBID='GOLD'
	;;
	gpweb09|gpweb10)
		SUBID='GALAXY'
	;;
	gpweb1[1-9])
		SUBID='PORTAL'
	;;
	gpweb2[0-5])
		SUBID='PLANT'
	;;
	gpweb26)
		SUBID='GENERAL'
	;;
	*)
		SUBID='GENERAL'
	;;
esac

if [ -z "$ID" ] || [ -z "$SUBID" ]; then
	echo PROBLEM: found no ID or SUBID
	exit
fi

pgrep -u $PROCUSER -f /usr/sbin/procmon >/dev/null
[ $? = 0 ] && exit

/usr/sbin/procmon -d -p 1 -u $PROCUSER -W 10 -f 30 -F 30 \
	-I $ID -S $SUBID --pid $PIDFILE
