#!/bin/bash

HN=$(hostname | sed -e 's/\..*//')

ID=
SUBID=

case $HN in
	gpweb*)
		ID='WEB'
	;;
	gpint*)
		ID='INT'
	;;
	genepool*)
		ID='LOGIN'
	;;
	*)
		ID='JGI'
	;;
esac

case $HN in
    gpint01)
        SUBID='RND'
    ;;
    gpint12)
        SUBID='RND'
    ;;
    gpint0[23])
        SUBID='VISTA'
    ;;
    gpint0[45])
        SUBID='IMG'
    ;;
    gpint0[6])
        SUBID='GBP'
    ;;
    gpint0[789])
        SUBID='PLANT'
    ;;
    gpint1[01])
        SUBID='PLANT'
    ;;
    gpint13)
        SUBID='FUNGAL'
    ;;
    gpint1[456789])
        SUBID='GENERAL'
    ;;
    gpint2[012])
        SUBID='GENERAL'
    ;;
    gpint2[367])
        SUBID='SDM'
    ;;
    gpint2[45])
        SUBID='RQC'
    ;;
	gpweb0[12])
		SUBID='VISTA'
	;;
	gpweb0[4567])
		SUBID='IMG'
	;;
	gpweb08)
		SUBID='GOLD'
	;;
	gpweb09|gpweb10)
		SUBID='GALAXY'
	;;
	gpweb1[1-9])
		SUBID='PORTAL'
	;;
	gpweb2[0-5])
		SUBID='PLANT'
	;;
	gpweb26)
		SUBID='GENERAL'
	;;
	*)
		SUBID='GENERAL'
	;;
esac

if [ -z "$ID" ] || [ -z "$SUBID" ]; then
		echo PROBLEM: bad hostname, $HN
		exit
fi

pgrep -u root /usr/sbin/procmon
if [ $? = 0 ]; then
	echo procmon already running, bailing
	exit
fi

/usr/sbin/procmon -d -p 1 -u procmon -f 30 -F 30 -W 10 -I $ID -S $SUBID
