# Makefile for procmon
# Author: Doug Jacobsen <dmjacobsen@lbl.gov>
# 2013/02/17
# 

INSTALL_PATH=/global/project/projectdirs/genepool/www/procmon

install: houseHunter.html
	chmod a+rX $^
	cp -p $^ $(INSTALL_PATH)
